# Generated by Django 5.0.6 on 2024-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='total_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
