# Generated by Django 5.0.6 on 2024-05-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_alter_parkinglot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='rfid_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
