# Generated by Django 5.0.6 on 2024-05-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0011_parkingrecord_rfid_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingrecord',
            name='rfid_code',
            field=models.CharField(default='441a9672', max_length=100),
        ),
    ]
