# Generated by Django 5.0.6 on 2024-05-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0014_payment_vnpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_vnpay',
            name='order_id',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
