# Generated by Django 5.0.6 on 2024-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0015_payment_vnpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='price_per_hour',
            field=models.IntegerField(max_length=10),
        ),
    ]
