# Generated by Django 5.0.6 on 2024-05-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0016_alter_parkinglot_price_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
