# Generated by Django 5.0.6 on 2024-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0017_temporarydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
