# Generated by Django 5.0.6 on 2024-06-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0018_parkinglot_latitude_parkinglot_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='longitude',
        ),
    ]
