# Generated by Django 5.0.6 on 2024-06-15 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0021_parkinglot_has_fire_alarm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_to',
            field=models.TimeField(),
        ),
    ]
