# Generated by Django 5.0.6 on 2024-06-15 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0022_remove_reservation_reservation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='projectApp.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateField(),
        ),
    ]
