# Generated by Django 5.0.6 on 2024-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0023_alter_reservation_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateField(null=True),
        ),
    ]
