# Generated by Django 5.0.6 on 2024-06-15 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0024_alter_reservation_reserved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
