# Generated by Django 5.0.6 on 2024-06-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0028_parkingspot_reservation_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qr_code_scanned',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
