# Generated by Django 5.0.6 on 2024-06-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0029_reservation_qr_code_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
